// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinimalAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905080000_AddGoogleSheetsAndOutbox")]
    partial class AddGoogleSheetsAndOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.1.25081.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinimalAPI.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Description").HasColumnType("text").HasColumnName("description");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("name");
                    b.Property<Guid>("StoreId").HasColumnType("uuid").HasColumnName("store_id");
                    b.HasKey("Id");
                    b.HasIndex("StoreId", "Name").IsUnique();
                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("MinimalAPI.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("Address").HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("address");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("email");
                    b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)").HasColumnName("name");
                    b.Property<string>("Phone").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasColumnName("phone");
                    b.Property<Guid>("StoreId").HasColumnType("uuid").HasColumnName("store_id");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.HasKey("Id");
                    b.HasIndex("StoreId");
                    b.HasIndex("StoreId", "Phone");
                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("MinimalAPI.Domain.Entities.GoogleSheetConnection", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("EncryptedRefreshToken").IsRequired().HasMaxLength(2048).HasColumnType("character varying(2048)").HasColumnName("encrypted_refresh_token");
                    b.Property<string>("LastErrorMessage").HasMaxLength(1000).HasColumnType("character varying(1000)").HasColumnName("last_error_message");
                    b.Property<DateTime?>("LastSyncAt").HasColumnType("timestamp with time zone").HasColumnName("last_sync_at");
                    b.Property<string>("SheetName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("sheet_name");
                    b.Property<string>("SpreadsheetId").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("spreadsheet_id");
                    b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("status");
                    b.Property<Guid>("StoreId").HasColumnType("uuid").HasColumnName("store_id");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.HasKey("Id");
                    b.HasIndex("StoreId").IsUnique();
                    b.ToTable("google_sheet_connections", (string)null);
                });

            modelBuilder.Entity("MinimalAPI.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("code");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<Guid>("CustomerId").HasColumnType("uuid").HasColumnName("customer_id");
                    b.Property<string>("Status").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)").HasColumnName("status");
                    b.Property<Guid>("StoreId").HasColumnType("uuid").HasColumnName("store_id");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalAmount", "MinimalAPI.Domain.Entities.Order.TotalAmount#Money", b1 =>
                        {
                            b1.IsRequired();
                            b1.Property<decimal>("Amount").HasColumnType("decimal(18,2)").HasColumnName("total_amount");
                            b1.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)").HasColumnName("currency");
                        });
                    b.HasKey("Id");
                    b.HasIndex("CustomerId");
                    b.HasIndex("StoreId");
                    b.HasIndex("StoreId", "Code").IsUnique();
                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("MinimalAPI.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<Guid>("OrderId").HasColumnType("uuid").HasColumnName("order_id");
                    b.Property<Guid>("ProductId").HasColumnType("uuid").HasColumnName("product_id");
                    b.Property<string>("ProductName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("product_name");
                    b.Property<int>("Quantity").HasColumnType("integer").HasColumnName("quantity");
                    b.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "MinimalAPI.Domain.Entities.OrderItem.UnitPrice#Money", b1 =>
                        {
                            b1.IsRequired();
                            b1.Property<decimal>("Amount").HasColumnType("decimal(18,2)").HasColumnName("unit_price_amount");
                            b1.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)").HasColumnName("unit_price_currency");
                        });
                    b.HasKey("Id");
                    b.HasIndex("OrderId");
                    b.HasIndex("ProductId");
                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("MinimalAPI.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<string>("Error").HasColumnType("text").HasColumnName("error");
                    b.Property<DateTime>("OccurredAt").HasColumnType("timestamp with time zone").HasColumnName("occurred_at");
                    b.Property<string>("Payload").IsRequired().HasColumnType("text").HasColumnName("payload");
                    b.Property<DateTime?>("ProcessedAt").HasColumnType("timestamp with time zone").HasColumnName("processed_at");
                    b.Property<int>("RetryCount").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("retry_count");
                    b.Property<Guid>("StoreId").HasColumnType("uuid").HasColumnName("store_id");
                    b.Property<string>("Type").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("type");
                    b.HasKey("Id");
                    b.HasIndex("StoreId");
                    b.HasIndex("ProcessedAt", "RetryCount");
                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("MinimalAPI.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<Guid>("CategoryId").HasColumnType("uuid").HasColumnName("category_id");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Description").HasColumnType("text").HasColumnName("description");
                    b.Property<bool>("IsActive").HasColumnType("boolean").HasColumnName("is_active");
                    b.Property<string>("Sku").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)").HasColumnName("sku");
                    b.Property<int>("StockQuantity").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0).HasColumnName("stock_quantity");
                    b.Property<Guid>("StoreId").HasColumnType("uuid").HasColumnName("store_id");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "MinimalAPI.Domain.Entities.Product.Name#ProductName", b1 =>
                        {
                            b1.IsRequired();
                            b1.Property<string>("Value").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)").HasColumnName("name");
                        });
                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "MinimalAPI.Domain.Entities.Product.Price#Money", b1 =>
                        {
                            b1.IsRequired();
                            b1.Property<decimal>("Amount").HasColumnType("decimal(18,2)").HasColumnName("price_amount");
                            b1.Property<string>("Currency").IsRequired().HasMaxLength(3).HasColumnType("character varying(3)").HasColumnName("price_currency");
                        });
                    b.HasKey("Id");
                    b.HasIndex("StoreId");
                    b.HasIndex("StoreId", "Sku").IsUnique();
                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("MinimalAPI.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)").HasColumnName("name");
                    b.Property<Guid>("OwnerId").HasColumnType("uuid").HasColumnName("owner_id");
                    b.Property<string>("Slug").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("slug");
                    b.HasKey("Id");
                    b.HasIndex("Slug").IsUnique();
                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("MinimalAPI.Domain.Entities.StoreMember", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid").HasColumnName("id");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("role");
                    b.Property<Guid>("StoreId").HasColumnType("uuid").HasColumnName("store_id");
                    b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.HasIndex("StoreId", "UserId").IsUnique();
                    b.ToTable("store_members", (string)null);
                });

            modelBuilder.Entity("MinimalAPI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)").HasColumnName("email");
                    b.Property<string>("FullName").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)").HasColumnName("full_name");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("text").HasColumnName("password_hash");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MinimalAPI.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("MinimalAPI.Domain.Entities.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinimalAPI.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
